config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: "reviews#index"
  
  resources :reviews do
   resources :comments, only: [:create, :destroy]
  end

  resources :users, only: :show
  post 'book/:id' => 'books#create', as: 'create_book'
  delete 'book/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :review
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--ジャンルを選択--' },
    { id: 2, name: '〜小説・評論〜' },
    { id: 3, name: '〜ビジネス・経済〜' },
    { id: 4, name: '〜歴史・古典〜' },
    { id: 5, name: '〜政治・社会〜' },
    { id: 6, name: '〜建築・デザイン〜' },
    { id: 7, name: '〜暮らし・料理〜' },
    { id: 8, name: '〜テクノロジー・サイエンス〜' },
    { id: 9, name: '〜教育・自己啓発〜' },
    { id: 10, name: '〜旅行・紀行〜' },
    { id: 11, name: '〜絵本・児童書〜' },
    { id: 12, name: '〜コミックス〜' },
    { id: 13, name: '〜ノンフィクション〜' }
  ]

    include ActiveHash::Associations
    has_many :reviews
  end

app/models/review.rb
class Review < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :books, dependent: :destroy
  has_one_attached :image
 
  with_options presence: true do
    validates :image
    validates :title
    validates :text, length: {maximum: 200}
    validates :genre_id, numericality: { other_than: 1 } 
    validates :rating, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }
  end

  def was_attached?
    image.attached?
  end

  def content_length
    content_for_validation = content.gsub(/\r\n/,"a")
    if content_for_validation.length >= 200
      errors.add(:content, "は200文字以内で入力してください。")
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments
  has_many :books

  validates :name, presence: true

  def liked_by?(review_id)
    books.where(review_id: review_id).exists?
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/book_marks_controller.rb
class Book_marksController < ApplicationController 

  def create
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :review_params

  def create
    Book.create(user_id: current_user.id, review_id: params[:id])
  end

  def destroy
    Book.find_by(user_id: current_user.id, review_id: params[:id]).destroy
  end


  private

  def review_params
    @review = Review.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    redirect_to "/reviews/#{@comment.review.id}"
  end

  def destroy
    @review = Review.find(params[:review_id])
    comment = @review.comments.find(params[:id])
    comment.destroy
    redirect_back(fallback_location: review_path)
    
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, review_id: params[:review_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :update, :edit]
  before_action :move_to_index, except: [:index, :show]


  def index
    @reviews = Review.all
    @reviews = Review.includes(:user).order("created_at DESC")
    query = "SELECT * FROM reviews"
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @review.update(review_params)
       redirect_to review_path
    else
       render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @review.comments.includes(:user)
  end

  def edit
    unless @review.user.id == current_user.id
      redirect_to action: :index
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to root_path
  end


  private
  def review_params
    params.require(:review).permit(:image, :title, :genre_id, :text, :rating).merge(user_id: current_user.id)
  end
  
  def set_review
    @review = Review.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
 
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @reviews = user.reviews
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.js.erb
document.getElementById('review_<%= @review.id %>').innerHTML = '<%= j(render partial: 'reviews/book', locals: {review: @review}) %>'

app/views/books/destroy.js.erb
document.getElementById('review_<%= @review.id %>').innerHTML = '<%= j(render partial: 'reviews/book', locals: {review: @review}) %>'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HonRevu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
  </head>

  <body>
      <header class="header">
          <div class="header_bar row">
              <h1 class="header-title"><a href="/">HonRevu</a></h1>
                <% if user_signed_in? %>
                  <div class="user_nav">
                      <div class="user_info">
                          <%= link_to current_user.name, "/users/#{current_user.id}" %>
                          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post" %>
                          <%= link_to "投稿する", new_review_path, class: "post" %>
                      </div>
                  </div>
                <% else %>
                  <div class="user_nav">
                      <div class="user_info">
                          <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "guest post" %>
                          <%= link_to "ログイン", new_user_session_path, class: "post" %>
                          <%= link_to "新規登録", new_user_registration_path, class: "post" %>
                      </div>
                  </div>
                <% end %>
          </div>
      </header>
    <%= yield %>
    <footer>
      <p>
        Copyright HonRevu 2021.
      </p>
    </footer> 
  </body>
</html>

app/views/reviews/_book.html.erb
<div class="content_footer">
    <div class="book_mark">
          <% if current_user.liked_by?(review.id) %>
            <%= link_to destroy_book_path(review), class: "like-link", method: :DELETE, remote: true do %> 
              <i class="fa fa-heart unlike-btn"></i>
            <% end %>
            <%= review.books.count %>
          <% else %>
            <%= link_to create_book_path(review), class: "like-link", method: :POST, remote: true do %>
              <i class="fa fa-heart like-btn"></i>
            <% end %>
            <%= review.books.count %>
          <% end %>
    </div>
    <div class="more">
      <%= link_to 'Show Review', review_path(review.id), method: :get %>
    </div>
</div>

app/views/reviews/_error_messages.html.erb
<% if model.errors.any? %>
    <div class="error-alert">
        <ul>
            <% model.errors.full_messages.each do |message| %>
               <li class='error-message'><%=message %>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="content_image">
    <%= link_to image_tag(review.image, class: "item-img"), review_path(review.id), method: :get %>
</div>
  <div class="content_header">
    <span>評価：</span>
      <div id="star-rate<%= review.id%>"></div>
        <script>
          $('#star-rate<%= review.id%>').raty({
            size      : 36,
            starOff   : '<%= asset_path('star-off.png') %>',
            starOn    : '<%= asset_path('star-on.png') %>',
            starHalf  : '<%= asset_path('star-half.png') %>',
            half      : true,
            readOnly: true,
            score: <%= review.rating %>,
          });
          $('#star-rate<%= review.id%>').css('padding', '10px');
        </script>
    <span>ジャンル：</span>
      <div class="content_genre">
        <%= review.genre.name %>
      </div>
    <span>タイトル：</span>
      <div class="content_title">
        <%= review.title %>
      </div>
    <span>レビュー：</span>
      <div class="content_text">
        <%= review.text %>
      </div>
  </div>

app/views/reviews/edit.html.erb
<div class="contents row">
    <div class="form-wrap">
         <div class="title-frame">投 稿 編 集</div>
          <%= form_with(model: @review, local: true) do |f| %>
          <%= render 'reviews/error_messages', model: @review %>
              <div class="form-group">
                <div class="form-text">画  像</div>
                  <div class="form-text-wrap">                      
                    <%= f.file_field :image, class: "form-image-box" %>
                  </div>
              </div>
              <div class="form-group">
                <div class="form-text">タイトル</div>
                  <div class="form-text-wrap">
                    <%= f.text_field :title, class: "form-box" %>
                  </div>
              </div>
              <div class="form-group">
                <div class="form-text">ジャンル</div>
                   <div class="form-text-wrap">
                     <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class: "form-box"}) %>
                   </div>
               </div>
               <div class="form-group">
                 <div class="form-text">投稿文</div>
                   <div class="form-text-wrap">
                     <%= f.text_area :text, class: "form-box", id: "input-text",rows: 4 %>
                   </div>
               </div>
              <%# <p class="text-counter" id="counter">0文字</p> %>
              <div class="form-group" id="star">
                  <div class="form-star-wrap">
                    <%= f.label :rating,  "星評価 (※必須)" ,id: "e", class: "form-box"%> 
                    <%= f.hidden_field :rating, id: :review_star %>
                      <script>
                        $('#star').raty({
                          size     : 36,
                          starOff:  '<%= asset_path('star-off.png') %>',
                          starOn :  '<%= asset_path('star-on.png') %>',
                          starHalf: '<%= asset_path('star-half.png') %>',
                          scoreName: 'review[rating]',
                          half: true,
                        });
                      </script> 
                  </div>
              </div> 
              <div class="submit">
                 <%= f.submit "Review!!", class:"submit-btn" %>
              </div>
        <% end %>
    </div>
</div>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
  <div class="contents row">
     <div class="content_post">
        <%= render 'review', review: review %>
         <div id="review_<%= review.id %>">
            <%= render 'book', review: review %>
         </div>
      </div>
   </div>
<% end %>

app/views/reviews/new.html.erb
<div class="contents row">
    <div class="form-wrap">
         <div class="title-frame">投 稿</div>
          <%= form_with(model: @review, local: true) do |f| %>
          <%= render 'reviews/error_messages', model: @review %>
              <div class="form-group">
                <div class="form-text">画  像</div>
                  <div class="form-text-wrap">                      
                    <%= f.file_field :image, class: "form-image-box" %>
                  </div>
              </div>
              <div class="form-group">
                <div class="form-text">タイトル</div>
                  <div class="form-text-wrap">
                    <%= f.text_field :title, class: "form-box" %>
                  </div>
              </div>
              <div class="form-group">
                <div class="form-text">ジャンル</div>
                   <div class="form-text-wrap">
                     <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class: "form-box"}) %>
                   </div>
               </div>
               <div class="form-group">
                 <div class="form-text">投稿文</div>
                   <div class="form-text-wrap">
                     <%= f.text_area :text, class: "form-box", id: "input-text",rows: 4 %>
                   </div>
               </div>
              <%# <p class="text-counter" id="counter">0文字</p> %>
              <div class="form-group" id="star">
                  <div class="form-star-wrap">
                    <%= f.label :rating,  "星評価 (※必須)" ,id: "e", class: "form-box"%> 
                    <%= f.hidden_field :rating, id: :review_star %>
                      <script>
                        $('#star').raty({
                          size     : 36,
                          starOff:  '<%= asset_path('star-off.png') %>',
                          starOn :  '<%= asset_path('star-on.png') %>',
                          starHalf: '<%= asset_path('star-half.png') %>',
                          scoreName: 'review[rating]',
                          half: true,
                        });
                      </script> 
                  </div>
              </div> 
              <div class="submit">
                 <%= f.submit "Review!!", class:"submit-btn" %>
              </div>
        <% end %>
    </div>
</div>

app/views/reviews/show.html.erb
<div class="contents row">
    <div class="content_post">
      <%= render 'review', review: @review %>
       <div class="more">
          <div class="more_list">
              <% if user_signed_in? && current_user.id == @review.user.id %>
                  <%= link_to 'Edit', edit_review_path(@review.id), method: :get %>
                  <%= link_to 'Deleate', review_path(@review.id), method: :delete %>
              <% end %>
          </div>
       </div>
    </div>
    <div class="comment_container">
        <% if current_user %>
          <%= form_with(model: [@review, @comment], local:true) do |form| %>
          <div class="comment_submit">
              <%= form.text_area :text, placeholder: "コメントする", class: "comment_content" %>
              <%= form.submit "SEND", class:"send_btn" %>
          </div>
          <% end %>
        <% else %>
          <strong><p>※ コメントの投稿には新規登録/ログインが必要です</p></strong>
        <% end %>
        <div class="comments">
          <h4 class="comment_title">【 コメント一覧 】</h4>
            <% if @comments %>
              <% @comments.each do |comment| %>
                <div class="comment_subject">
                    <div class="comment_name">
                      <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %></strong>
                    </div>
                    <div class="comment_text">
                      <%= comment.text %>
                    </div>
                    <div class="action">
                      <% if current_user.id == comment.user_id %>
                        <%= link_to '削 除', review_comment_path(@review, comment), method: :delete, class:"delete-btn" %>
                      <% end %>
                    </div>
                </div>
              <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @name %>さんの投稿一覧</p>
    <% @reviews.each do |review| %>
        <div class="content_post">
            <div class="content_image">
              <%= link_to image_tag(review.image, class: "item-img"), review_path(review.id), method: :get %>
            </div>
            <div class="content_header">
              <span>評価：</span>
            <div id="star-rate<%= review.id%>"></div>    
                <script>
                  $('#star-rate<%= review.id%>').raty({
                    size      : 36,
                    starOff   : '<%= asset_path('star-off.png') %>',
                    starOn    : '<%= asset_path('star-on.png') %>',
                    starHalf  : '<%= asset_path('star-half.png') %>',
                    half      : true,
                    readOnly: true,
                    score: <%= review.rating %>,
                  });
                  $('#star-rate<%= review.id%>').css('padding', '10px');
                </script>
                <span>ジャンル：</span>
                <div class="content_genre">
                  <%= review.genre.name %>
                </div>
                <span>タイトル：</span>
                <div class="content_title">
                  <%= review.title %>
                </div>
              </div>
              <span>レビュー：</span>
                <div class="content_text">
                  <%= review.text %>
                </div>
            </div>
        </div>
    <% end %>
</div>